"""Configuration for XGBoost entity matching pipeline.

All paths are relative to the repository root or can be overridden via CLI.
"""
from __future__ import annotations
from dataclasses import dataclass, field, asdict
from typing import Optional
import os


@dataclass(frozen=True)
class XGBoostConfig:
    # --- Data paths (relative to repo root or absolute) ---
    # Local Windows paths for D:\Amazon_challenge_ML setup
    data_root: str = os.environ.get(
        "AMLC_DATA_ROOT",
        r"D:\Amazon_challenge_ML\Amazon-ML-dataset\student_resource\dataset"
    )
    # Candidate pairs generated by the blocking pipeline
    candidates_path: str = os.environ.get(
        "AMLC_CANDIDATES_PATH",
        r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\blocking\candidate_pairs.tsv"
    )
    # Ground truth (train only)
    ground_truth_path: str = os.environ.get(
        "AMLC_GROUND_TRUTH_PATH",
        r"D:\Amazon_challenge_ML\Amazon-ML-dataset\student_resource\dataset\train\train_ground_truth.tsv"
    )
    # Source data files (for joining features)
    train_s1_path: str = r"D:\Amazon_challenge_ML\Amazon-ML-dataset\student_resource\dataset\train\train_source1.tsv"
    train_s2_path: str = r"D:\Amazon_challenge_ML\Amazon-ML-dataset\student_resource\dataset\train\train_source2.tsv"
    train_s3_path: str = r"D:\Amazon_challenge_ML\Amazon-ML-dataset\student_resource\dataset\train\train_source3.tsv"

    # --- Output paths ---
    output_dir: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs"
    model_path: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs\models\xgboost_model.json"
    model_pkl_path: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs\models\xgboost_model.pkl"
    val_predictions_path: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs\predictions\validation_predictions.csv"
    metrics_path: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs\metrics\metrics.json"
    threshold_results_path: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs\metrics\threshold_results.csv"
    best_threshold_path: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs\metrics\best_threshold.json"
    eval_report_path: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs\reports\evaluation_report.md"
    error_analysis_path: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs\reports\error_analysis.csv"
    feature_importance_path: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs\feature_importance\feature_importance.csv"
    experiment_config_path: str = r"D:\Amazon_challenge_ML\amazon-ml-hackathon-26\training\xgboost\outputs\metrics\experiment_config.json"

    # --- Train/Validation split ---
    # Split by S1 entity to avoid leakage (same S1 entity in both train and val)
    val_split_ratio: float = 0.15
    val_split_seed: int = 20260926
    # If True, use a fixed validation set based on S1 entity hash
    # This ensures reproducibility and no overlap of S1 entities
    stratified_by_country: bool = True

    # --- Feature engineering ---
    # Name features
    use_name_exact: bool = True
    use_name_jaro: bool = True
    use_name_jarowinkler: bool = True
    use_name_levenshtein: bool = True
    use_name_token_jaccard: bool = True
    use_name_token_dice: bool = True
    use_name_token_set_ratio: bool = True
    use_name_token_sort_ratio: bool = True
    use_name_char_ngram_jaccard: bool = True
    use_name_tfidf_cosine: bool = False  # Requires pre-fitted vectorizer

    # Address features
    use_addr_exact: bool = True
    use_addr_token_jaccard: bool = True
    use_addr_token_dice: bool = True
    use_addr_char_jaccard: bool = True
    use_addr_levenshtein: bool = True
    use_addr_tfidf_cosine: bool = False
    use_addr_city_match: bool = True
    use_addr_postal_match: bool = True
    use_addr_housenumber_match: bool = True

    # Phone features (if available in address field)
    use_phone_exact: bool = True
    use_phone_normalized: bool = True
    use_phone_suffix: bool = True
    use_phone_missing: bool = True

    # Other features
    use_country_match: bool = False  # Constant within partition - PROJECT_CONTEXT Finding 10
    use_cross_script: bool = True
    use_transliteration_sim: bool = True
    use_blocker_rank: bool = True
    use_blocker_score: bool = True
    use_blocker_passes: bool = True
    use_missing_indicators: bool = True

    # Group-relative features (computed per S1 entity's candidate group)
    use_group_rank: bool = True
    use_group_margin_to_2nd: bool = True
    use_group_score_ratio_to_max: bool = True
    use_group_size: bool = True
    use_is_mutual_best: bool = True
    use_n_competitors: bool = True

    # Cross-field features
    use_name_high_addr_low: bool = True
    use_name_low_addr_high: bool = True
    use_sim_disagreement: bool = True

    # Missingness encoding (NaN for trees, not 0)
    encode_missing_as_nan: bool = True

    # --- XGBoost parameters ---
    xgb_params: dict = field(default_factory=lambda: {
        "objective": "binary:logistic",
        "eval_metric": "logloss",
        "learning_rate": 0.03,
        "max_depth": 6,
        "min_child_weight": 1,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "reg_alpha": 0.0,
        "reg_lambda": 1.0,
        "random_state": 20260926,
        "n_jobs": -1,
        "tree_method": "hist",
        "enable_categorical": False,
        "verbosity": 1,
    })
    num_boost_round: int = 2000
    early_stopping_rounds: int = 100

    # Class imbalance handling
    # Use scale_pos_weight = neg/pos (XGBoost native)
    use_scale_pos_weight: bool = True

    # --- Threshold optimization ---
    threshold_grid: list = field(default_factory=lambda: [
        0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50,
        0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90
    ])

    # --- Evaluation ---
    # Competition metric: macro-averaged F0.5 per S1 entity
    # Also compute: Precision, Recall, F1, PR-AUC, Top-1, Top-K, confusion matrix
    compute_macro_f05: bool = True
    compute_pr_auc: bool = True
    compute_top_k: bool = True
    top_k_values: tuple = (1, 3, 5, 10)

    # --- Reproducibility ---
    seed: int = 20260926

    # --- Experiment tracking ---
    experiment_name: str = "xgboost_baseline"
    experiment_timestamp: str = ""  # Set at runtime

    def to_dict(self) -> dict:
        return asdict(self)

    def resolve_path(self, path: str) -> str:
        """Resolve a path relative to repo root if not absolute."""
        if os.path.isabs(path):
            return path
        # Find repo root (directory containing PROJECT_CONTEXT.md)
        repo_root = os.getcwd()
        while repo_root != os.path.dirname(repo_root):
            if os.path.exists(os.path.join(repo_root, "PROJECT_CONTEXT.md")):
                break
            repo_root = os.path.dirname(repo_root)
        return os.path.join(repo_root, path)


def get_config(**overrides) -> XGBoostConfig:
    """Create config with optional overrides."""
    base = XGBoostConfig()
    if overrides:
        # Create new instance with overrides
        d = base.to_dict()
        d.update(overrides)
        return XGBoostConfig(**d)
    return base